### ISSUE TITLE
How to get the final HDR image for visualization?

### ISSUE THREAD

**Issue by CaptainEven** [chxy95/HDRUNet#5]
Is the code 
```
img = io.imread_uint16_png(img_path, alignratio_path)
img = np.clip(np.tanh(img), 0, 1) * 255
img = img.round().astype(np.uint8)
cv2.imwrite(save_path, cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
```
enough for converting output to HDR image?

**Comment by chxy95** [comment]
@CaptainEven Hello, if your data are paired, you can use the μ-law tone-mapping provided by the competition organizer (we also use this tone-mapping method in this repo). Otherwise, you should use the tone-mapping algorithms without reference for visualization. The abovementioned script is only used for an approximate visualization.

**Comment by CaptainEven** [comment]
@chxy95 Thanks for the replying!
